export const fundamentos = [
  {
    id: 1,
    name: 'Leassons Learned',
    link: 'https://github.com/tryber/sd-08-project-lessons-learned/pull/34',
    techs: ['HTML', 'CSS'],
    description: 'Foram utilizadas as principais tags HTML para compor a estrutura da página e foi estilizado através de CSS. O objetivo foi consolidar todo o conhecimento adquirido com a produção completa de um site.',
  },
  {
    id: 2,
    name: 'Playground Functions',
    link: 'https://github.com/tryber/sd-08-project-playground-function/pull/9',
    techs: ['JavaScript'],
    description: 'Foram implementadas uma série de funções em JavaScript, para entender a importância de saber quebrar grandes problemas em problemas menores e utilizar a lógica de programação na resolução.',
  },
  {
    id: 3,
    name: 'Pixels Art',
    link: 'https://github.com/tryber/sd-08-project-pixels-art/pull/40',
    deploy: 'https://victorfariass.github.io/pixels-art/',
    techs: ['HTML', 'CSS', 'JavaScript'],
    description: 'Foi implementado um editor de arte com pixels. Ou seja, dada uma paleta de cores e um quadro composto por pixels, permite que quem usa consiga pintar o que quiser no quadro.',
  },
  {
    id: 4,
    name: 'To do List',
    link: 'https://github.com/tryber/sd-08-project-todo-list/pull/37',
    deploy: 'https://victorfariass.github.io/todo-list/',
    techs: ['HTML', 'CSS', 'JavaScript'],
    description: 'Nesse projeto foi necessário manipular o DOM para adicionar (ou remover) itens à lista de tarefas, utilizar eventos para identificar quando o usuário está interagindo com a página e criar funções para tratar esses eventos de forma apropriada.',
  },
  {
    id: 5,
    name: 'Facebook Signup',
    link: 'https://github.com/tryber/sd-08-project-facebook-signup/pull/30',
    deploy: 'https://victorfariass.github.io/login-signup/',
    techs: ['HTML', 'CSS', 'JavaScript'],
    description: 'Foi implementado um formulário em HTML, utilizando também bibliotecas que deixou o trabalho mais rápido, fácil e bonito. Além disso, foi estilizado usando muito CSS Flexbox, que é uma maneira fácil e limpa de organizar os elementos da tela.'
  },
  {
    id: 6,
    name: 'Unit Tests',
    link: 'https://github.com/tryber/sd-08-project-js-unit-tests/pull/31',
    techs: ['JavaScript', 'Node.js'],
    description: 'Foram implementadas funções a partir de requisitos e testes unitários, utilizando o módulo Assert do NodeJS para verificar o correto funcionamento dessas funções.',
  },
  {
    id: 7,
    name: 'Zoo Functions',
    link: 'https://github.com/tryber/sd-08-project-zoo-function/pull/109',
    techs: ['JavaScript'],
    description: 'Nesse projeto foi implementado um conjunto de funções para recuperar informações de um zoológico, utilizando as funcionalidades do JavaScript ES6.',
  },
  {
    id: 8,
    name: 'Shopping Cart',
    link: 'https://github.com/tryber/sd-08-project-shopping-cart/pull/60',
    deploy: 'https://victorfariass.github.io/shopping-cart/',
    techs: ['HTML', 'CSS', 'JavaScript'],
    description: 'Este projeto coloca em prática todo o conteúdo sobre Web Storage e assincronicidade em JavaScript.',
  },
  {
    id: 9,
    name: 'Jest',
    link: 'https://github.com/tryber/sd-08-project-jest/pull/20',
    techs: ['JavaScript', 'Jest'],
    description: 'Foram implementados testes utilizando o Jest para verificar o correto funcionamento de uma série de funções.',
  },
]

export const frontend = [
  {
    id: 1,
    name: 'Movie Cards Library',
    link: 'https://github.com/tryber/sd-08-project-movie-cards-library/pull/13',
    deploy: 'https://victorfariass.github.io/movie-cards-library/',
    techs: ['JavaScript', 'React', 'CSS'],
    description: 'Foi desenvolvido uma biblioteca de cartões contendo informações sobre filmes. Foi ultilizado o React e alguns conceitos básicos: componentes, props e composição de componentes.',
  },
  {
    id: 2,
    name: 'Movie Cards Library Stateful',
    link: 'https://github.com/tryber/sd-08-project-movie-cards-library-stateful/pull/13',
    deploy: 'https://victorfariass.github.io/movie-cards-library-statefull/',
    techs: ['JavaScript', 'React', 'CSS'],
    description: 'Esse projeto é igual ao anterior, porém usa a funcionalidade de estados de componentes em React.',
  },
  {
    id: 3,
    name: 'Movie Cards Library CRUD',
    link: 'https://github.com/tryber/sd-08-project-movie-cards-library-crud/pull/34',
    deploy: 'https://victorfariass.github.io/movie-cards-library-crud',
    techs: ['JavaScript', 'React', 'CSS'],
    description: 'Esse projeto é igual aos anteriores, porém utiliza a biblioteca React Router para organizar a aplicação em rotas e fornecer formas de navegar entre elas.',
  },
  {
    id: 4,
    name: 'Frontend Online Store',
    link: 'https://github.com/tryber/sd-08-project-frontend-online-store/pull/45',
    deploy: 'https://victorfariass.github.io/project-frontend-online-store/',
    techs: ['JavaScript', 'React', 'CSS'],
    description: 'Primeiro projeto feito em grupo, utilizando todos os conceitos aprendidos em React e as Metodologias Ágeis.',
  },
  {
    id: 5,
    name: 'React Testing Library',
    link: 'https://github.com/tryber/sd-08-project-react-testing-library/pull/32',
    deploy: 'https://victorfariass.github.io/pokedex',
    techs: ['JavaScript', 'React'],
    description: 'Neste projeto foi escrito testes para uma aplicação em React.',
  },
  {
    id: 6,
    name: 'Trybe Wallet',
    link: 'https://github.com/tryber/sd-08-project-trybewallet/pull/21',
    deploy: 'https://victorfariass.github.io/wallet/',
    techs: ['JavaScript', 'React', 'Redux', 'CSS'],
    description: 'Neste projeto foi desenvolvido uma carteira de controle de gastos com conversor de moedas, utilizando Redux para o compartilhamento de estado entre os componentes.',
  },
  {
    id: 7,
    name: 'Jogo de Trivia',
    link: 'https://github.com/tryber/sd-08-project-trivia-react-redux/pull/10',
    deploy: 'https://victorfariass.github.io/game-quest/',
    techs: ['JavaScript', 'React', 'Redux', 'CSS'],
    description: 'Foi desenvolvido um jogo de perguntas e respostas baseado no jogo Trivia utilizando React e Redux, desenvolvendo em grupo suas funcionalidades de acordo com as demanas definidas em um quadro Kanban.',
  },
  {
    id: 8,
    name: 'StarWars Planets Search',
    link: 'https://github.com/tryber/sd-08-project-starwars-planets-search/pull/32',
    deploy: 'https://victorfariass.github.io/starwars-planets-search/',
    techs: ['JavaScript', 'React', 'Context API', 'Hooks', 'CSS'],
    description: 'Foi desenvolvido uma lista com filtros de planetas do universo de Star Wars usando Context API e Hooks para controlar os estados globais.',
  },
  {
    id: 9,
    name: 'App de Receitas',
    link: 'https://github.com/tryber/sd-08-project-recipes-app/pull/56',
    deploy: 'https://victorfariass.github.io/recipes/',
    techs: ['JavaScript', 'React', 'Context API', 'Hooks', 'CSS'],
    description: 'Foi desenvolvido um app de receitas, utilizando o que há de mais moderno dentro do ecossistema React: Hooks e Context API! Nela é possível ver, buscar, filtrar, favoritar e acompanhar o processo de preparação de receitas e drinks!',
  },
]

export const backend = [
  {
    id: 1,
    name: 'All For One',
    link: 'https://github.com/tryber/sd-08-mysql-all-for-one/pull/73',
    techs: ['MySQL'],
    description: 'Neste projeto foi praticado todos os conceitos de SQL.',
  },
  {
    id: 2,
    name: 'Vocabulary Booster',
    link: 'https://github.com/tryber/sd-08-mysql-vocabulary-booster/pull/4',
    techs: ['MySQL'],
    description: 'Neste projeto foram praticados todos os conceitos de SQL e a criação de queries mais elaboradas, utilizando, muitas vezes, diferentes comandos em uma mesma query.',
  },
  {
    id: 3,
    name: 'One For All',
    link: 'https://github.com/tryber/sd-08-mysql-one-for-all/pull/23',
    techs: ['MySQL'],
    description: 'Neste projeto foi usado uma tabela para revisar e consolidar todos os principais conceitos vistos sobre SQL.',
  },
  {
    id: 4,
    name: 'Data Flights',
    link: 'https://github.com/tryber/sd-08-mongodb-dataflights/pull/30',
    techs: ['MongoDB'],
    description: 'Neste projeto, temos uma série de desafios com diferentes níveis de complexidade que devem ser resolvidos cada um em seu arquivo próprio para praticar MongoDB.',
  },
  {
    id: 5,
    name: 'Commerce',
    link: 'https://github.com/tryber/sd-08-mongodb-commerce/pull/10',
    techs: ['MongoDB'],
    description: 'Neste projeto, foi praticado todos os conceitos de MongoDB.',
  },
  {
    id: 6,
    name: 'Aggregations',
    link: 'https://github.com/tryber/sd-08-mongodb-aggregations/pull/41',
    techs: ['MongoDB'],
    description: 'Neste projeto, foram utilizados vários datasets, de forma que possa praticar em vários cenários os diversos operadores e estágios do aggregation pipeline.',
  },
  {
    id: 7,
    name: 'Talker Manager',
    link: 'https://github.com/tryber/sd-08-project-talker-manager/pull/3',
    techs: ['JavaScript', 'NodeJs'],
    description: 'Foi desenvolvido uma API de um CRUD (Create, Read, Update e Delete) de palestrantes. Foi desenvolvido alguns endpoints que irão ler e escrever em um arquivo, isso utilizando o módulo fs.',
  },
  {
    id: 8,
    name: 'Store Manager',
    link: 'https://github.com/tryber/sd-08-store-manager/pull/21',
    techs: ['JavaScript', 'NodeJs', 'MongoDB'],
    description: 'Foi desenvolvido uma API utilizando a arquitetura MSC. A API construída trata-se de um sistema de gerenciamento de vendas, onde é possível criar, visualizar, deletar e atualizar produtos e vendas.',
  },
  {
    id: 9,
    name: 'Cookmaster',
    link: 'https://github.com/tryber/sd-08-cookmaster/pull/17',
    techs: ['JavaScript', 'NodeJs', 'MongoDB'],
    description: 'Neste projeto é possível fazer o cadastro e login de pessoas usuárias, onde apenas essas pessoas poderão acessar, modificar e deletar as receitas que cadastrou.',
  },
  {
    id: 10,
    name: 'API de Blogs',
    link: 'https://github.com/tryber/sd-08-project-blogs-api/pull/33',
    techs: ['JavaScript', 'NodeJs', 'MySQL', 'Sequelize'],
    description: 'Foi arquiteturado e desenvolvido uma API de um CRUD posts de blog (com o sequelize).',
  },
  {
    id: 11,
    name: 'Webchat',
    link: 'https://github.com/tryber/sd-08-project-blogs-api/pull/33',
    techs: ['JavaScript', 'NodeJs', 'MongoDB', 'Socket.io'],
    description: 'Neste projeto foi desenvolvido um chat online utilizando sockets para o envio de mensagens em tempo real.',
  },
  {
    id: 12,
    name: 'App de Delivery',
    link: 'https://github.com/tryber/sd-08-project-delivery-app/pull/7',
    techs: ['JavaScript', 'NodeJs', 'MySQL', 'React', 'Redux', 'CSS'],
    description: 'Neste projeto foi criado e integrado, tanto o back-end quanto o front-end, uma plataforma de delivery de cerveja.',
  },
]

export const hardSkills = [
  'Git',
  'GitHub',
  'HTML',
  'CSS',
  'JavaScript',
  'Jest',
  'ReactJS',
  'Redux',
  'Context API',
  'MySQL',
  'MongoDB',
  'NodeJs',
  'Heroku',
  'Sequelize',
  'Socket.io',
]

export const softSkills = [
  {
    trilha: 'Inteligência Emocional',
    skills: ['Autoconhecimento', 'Empatia', 'Resiliência', 'Autogestão'],
  },
  {
    trilha: 'Comunicação',
    skills: ['Escuta Ativa', 'Assertividade', 'Dar e Receber Feedbacks', 'Negociação',],
  },
  {
    trilha: 'Colaboração',
    skills: ['Senso de Time'],
  },
  {
    trilha: 'Pensamento Crítico',
    skills: ['Resolução de Problemas', 'Raciocínio Lógico', 'Tomada de Decisão'],
  },
  {
    trilha: 'Criatividade',
    skills: ['Inovação', 'Criação', 'Curiosidade'],
  },
  {
    trilha: 'Liderança',
    skills: ['Organização'],
  }
]
